package server.interfaces;

public interface ServerHeaderCommands {
    String PARSE_ERROR = "PARSE_ERROR";
    String READY = "READY";
    String ENTER = "ENTER";
    String BROADCAST_REQ = "BROADCAST_REQ";
    String CHALLENGE_REQ = "CHALLENGE_REQ";
    String CHALLENGE_RESP = "CHALLENGE_RESP";
    String USER_LIST_REQ = "USER_LIST_REQ";
    String PONG = "PONG";
    String PRIVATE_MESSAGE_REQ = "PRIVATE_MESSAGE_REQ";
    String CHALLENGE_NOTIFICATION = "CHALLENGE_NOTIFICATION";
    String ENTER_RESP = "ENTER_RESP";
    String BROADCAST = "BROADCAST";
    String BROADCAST_RESP = "BROADCAST_RESP";
    String PING = "PING";
    String USER_LIST_RESP = "USER_LIST_RESP";
    String JOINED = "JOINED";
    String CHALLENGE_COMPLETE_NOTIFICATION = "CHALLENGE_COMPLETE_NOTIFICATION";
    String CHALLENGE_START = "CHALLENGE_START";
    String PRIVATE_MESSAGE_RESP = "PRIVATE_MESSAGE_RESP";
    String PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
    String ERROR = "ERROR";
    String SUCCESS = "SUCCESS";
}
